## The exponential of a matrix
Let $A$ be an $n\times n$ matrix.  Recall that
$$
    X(t) = e^{At} = I + At + {A^2t^2\over 2} + {A^3t^3\over 3!} +\ldots = \sum_{k=0}^{\infty} {A^kt^k\over k!}
$$
is a fundamental matrix solution of
$$
    \boldsymbol y' = A\boldsymbol y
$$
and
$$
    \left(X(t)\right)^{-1} = X(-t) = e^{-At}.
$$

## Canonical Forms
Suppose $A$ is similar to $J$.  That is, suppose there is an invertible matrix $P$ such that 
$$
    AP = PJ\qquad\hbox{or}\qquad A = PJP^{-1}
$$
then
$$
    e^{At} = P e^{Jt} P^{-1}.
$$

## Complex Eigenvalues
Suppose
$$
    J = \begin{bmatrix} \alpha & \beta\cr -\beta & \alpha \cr\end{bmatrix}
    = \alpha \begin{bmatrix} 1 & 0 \\ 0 & 1\end{bmatrix} 
     + \beta \begin{bmatrix} 0 & 1\cr -1 & 0 \cr\end{bmatrix} = \alpha I + \beta B.
$$
Since the identity matrix commutes with any $2\times2$ matrix,
$$
    e^{Jt} = e^{\alpha I t} e^{B t}.
$$
Furthermore
$$
    e^{Jt} = e^{\alpha I t}e^{Bt} = e^{\alpha t}\begin{bmatrix}
    \cos \beta t & \sin\beta t\cr
    -\sin\beta t & \cos\beta t\cr
    \end{bmatrix}
$$

## Block Diagonal Matrices

If $J$ is a block diagonal matrix, say
$$
    J = \begin{bmatrix}
        J_1 & 0 & 0 & \cdots & 0 \\
        0 & J_2 & 0 & \cdots & 0 \\
        0 & 0 & J_3 & \cdots & 0 \\
        \vdots & \vdots & \vdots & \ddots & \vdots \\
        0 & 0 & 0 &\cdots &J_m\\
    \end{bmatrix}
$$
where each $J_i$ is a square matrix, then

$$
    J^kt^k = \begin{bmatrix}
        J_1^k t^k & 0 & 0 & \cdots & 0 \\
        0 & J_2^k t^k & 0 & \cdots & 0 \\
        0 & 0 & J_3^k t^k & \cdots & 0 \\
        \vdots & \vdots & \vdots & \ddots & \vdots \\
        0 & 0 & 0 &\cdots &J_m^k t^k\\
    \end{bmatrix}
$$

and
$$
    e^{Jt} = \sum_{k=0}^{\infty} {J^k t^k\over k!}
    =\begin{bmatrix} 
        e^{J_1 t} & 0 & 0 & \cdots & 0 \\
        0 & e^{J_2 t} & 0 & \cdots & 0 \\
        0 & 0 & e^{J_3 t} & \cdots & 0 \\
        \vdots & \vdots & \vdots & \ddots & \vdots \\
        0 & 0 & 0 &\cdots &e^{J_m t}\\
    \end{bmatrix}
$$

In [1]:
import numpy as np, math
import numpy.linalg as LA
from math import pi as π
from sympy import Symbol, Matrix, diag, diff, exp, cos, sin, factor

## Differential Equation:
$$
    y^{(8)}+8y^{(7)}+22y^{(6)}+22y^{(5)}+7y^{(4)}+34y^{(3)}+90 y^{(2)}+80 y'+24 y= 0
$$
Equivalent first order system
\begin{align*}
\dot y = \dot y_1 &= y_2\cr
\dot y_2 &= y_3\cr
&\vdots\cr
\dot y_7 &=y_8\cr
\dot y_8 &= - 8y_8-22y_7-22y_6-7y_5-34y_4-90y_3-80y_2-24y_1\cr
\end{align*}

In [2]:
A = np.eye(8,8,1,dtype=int)
A[-1] = [-24,-80,-90,-34,-7,-22,-22,-8]
A

array([[  0,   1,   0,   0,   0,   0,   0,   0],
       [  0,   0,   1,   0,   0,   0,   0,   0],
       [  0,   0,   0,   1,   0,   0,   0,   0],
       [  0,   0,   0,   0,   1,   0,   0,   0],
       [  0,   0,   0,   0,   0,   1,   0,   0],
       [  0,   0,   0,   0,   0,   0,   1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   1],
       [-24, -80, -90, -34,  -7, -22, -22,  -8]])

In [3]:
λ,V = LA.eig(A)
λ

array([-3.        +0.00000000e+00j,  1.        +1.00000000e+00j,
        1.        -1.00000000e+00j, -2.00000007+0.00000000e+00j,
       -1.99999993+0.00000000e+00j, -1.00001484+0.00000000e+00j,
       -0.99999258+1.28500039e-05j, -0.99999258-1.28500039e-05j])

In [4]:
Matrix(A).eigenvals()

{-3: 1, -2: 2, -1: 3, 1 - I: 1, 1 + I: 1}

### Eigenvalue -1
This eigenvalue has algebraic multiplicity 3, but what is the geometric multiplicity?  This must be the dimension of the nullspace of 
$A+I.$

In [5]:
I8 = np.eye(8,dtype=int)
λ1 = -1
w1 = np.array([-2,2,-2, 2,-2, 2, -2,  2])
w2 = np.array([-3,1, 1,-3, 5,-7,  9,-11])
w3 = np.array([-3,0, 1, 0,-3, 8,-15, 24])
w1w2w3 = np.vstack((w1,w2,w3)).T
w1w2w3

array([[ -2,  -3,  -3],
       [  2,   1,   0],
       [ -2,   1,   1],
       [  2,  -3,   0],
       [ -2,   5,  -3],
       [  2,  -7,   8],
       [ -2,   9, -15],
       [  2, -11,  24]])

In [6]:
LA.matrix_rank(w1w2w3)

np.int64(3)

In [7]:
J1 = np.array([[λ1,1,0],[0,λ1,1],[0,0,λ1]])
J1

array([[-1,  1,  0],
       [ 0, -1,  1],
       [ 0,  0, -1]])

In [8]:
A@w1w2w3 - w1w2w3@J1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Eigenvalue -2

In [9]:
λ2 = -2
w4 = 3*np.array([ 1, -2, 4, -8,16,-32,64,-128])
w5 =   np.array([10,-17,28,-44,64,-80,64,  64])
w4w5 = np.vstack((w4,w5)).T
w4w5

array([[   3,   10],
       [  -6,  -17],
       [  12,   28],
       [ -24,  -44],
       [  48,   64],
       [ -96,  -80],
       [ 192,   64],
       [-384,   64]])

In [10]:
LA.matrix_rank(w4w5)

np.int64(2)

In [11]:
J2 = np.array([[-2,1],[0,-2]])
J2

array([[-2,  1],
       [ 0, -2]])

In [12]:
A@w4w5 - w4w5@J2

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

## Eigenvector -3

In [20]:
w6 = np.array([[1,-3,9,-27,81,-243,729,-2187]]).T
A@w6 + 3*w6

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [21]:
J3 = np.array([[-3]])
J3

array([[-3]])

In [24]:
A@w6 - w6@J3

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

### Eigenvalue $\lambda = 1+i$ of multiplicity $1$

In [25]:
α,β = 1,1
λ,V = LA.eig(A)
λ

array([-3.        +0.00000000e+00j,  1.        +1.00000000e+00j,
        1.        -1.00000000e+00j, -2.00000007+0.00000000e+00j,
       -1.99999993+0.00000000e+00j, -1.00001484+0.00000000e+00j,
       -0.99999258+1.28500039e-05j, -0.99999258-1.28500039e-05j])

In [27]:
v78 = V.T[1]
v78/v78[0].real

array([ 1.00000000e+00+1.00000000e+00j, -2.58340284e-15+2.00000000e+00j,
       -2.00000000e+00+2.00000000e+00j, -4.00000000e+00-2.52601931e-15j,
       -4.00000000e+00-4.00000000e+00j,  1.33956271e-14-8.00000000e+00j,
        8.00000000e+00-8.00000000e+00j,  1.60000000e+01+0.00000000e+00j])

In [28]:
u = np.array([1,0,-2,-4,-4,0,8,16])
v = np.array([1,2,2,0,-4,-8,-8,0])
uv = np.vstack((u,v)).T
uv

array([[ 1,  1],
       [ 0,  2],
       [-2,  2],
       [-4,  0],
       [-4, -4],
       [ 0, -8],
       [ 8, -8],
       [16,  0]])

In [29]:
J4 = np.array([[α,β],[-β,α]])
J4

array([[ 1,  1],
       [-1,  1]])

In [30]:
A@uv - uv@J4

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [31]:
P = np.hstack([w1w2w3,w4w5,w6,uv])
P

array([[   -2,    -3,    -3,     3,    10,     1,     1,     1],
       [    2,     1,     0,    -6,   -17,    -3,     0,     2],
       [   -2,     1,     1,    12,    28,     9,    -2,     2],
       [    2,    -3,     0,   -24,   -44,   -27,    -4,     0],
       [   -2,     5,    -3,    48,    64,    81,    -4,    -4],
       [    2,    -7,     8,   -96,   -80,  -243,     0,    -8],
       [   -2,     9,   -15,   192,    64,   729,     8,    -8],
       [    2,   -11,    24,  -384,    64, -2187,    16,     0]])

In [32]:
Matrix(P).det()

244800000

In [33]:
J = diag(J1,J2,J3,J4)
J

Matrix([
[-1,  1,  0,  0,  0,  0,  0, 0],
[ 0, -1,  1,  0,  0,  0,  0, 0],
[ 0,  0, -1,  0,  0,  0,  0, 0],
[ 0,  0,  0, -2,  1,  0,  0, 0],
[ 0,  0,  0,  0, -2,  0,  0, 0],
[ 0,  0,  0,  0,  0, -3,  0, 0],
[ 0,  0,  0,  0,  0,  0,  1, 1],
[ 0,  0,  0,  0,  0,  0, -1, 1]])

In [34]:
A@P - P@J

Matrix([
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
t = Symbol('t')
expJ4t = exp(α*t)*Matrix([[cos(β*t),sin(β*t)],[-sin(β*t),cos(β*t)]])
expJ4t

Matrix([
[ exp(t)*cos(t), exp(t)*sin(t)],
[-exp(t)*sin(t), exp(t)*cos(t)]])

In [36]:
expJ3t = Matrix([[exp(-3*t)]])
expJ3t

Matrix([[exp(-3*t)]])

In [41]:
expJ2t = exp(λ2*t)*Matrix([[1,t],[0,1]])
expJ2t

Matrix([
[exp(-2*t), t*exp(-2*t)],
[        0,   exp(-2*t)]])

In [39]:
expJ1t = exp(λ1*t) * Matrix([[1,t,t**2/2],[0,1,t],[0,0,1]])
expJ1t

Matrix([
[exp(-t), t*exp(-t), t**2*exp(-t)/2],
[      0,   exp(-t),      t*exp(-t)],
[      0,         0,        exp(-t)]])

In [42]:
expJt = diag(expJ1t,expJ2t,expJ3t,expJ4t)
expJt

Matrix([
[exp(-t), t*exp(-t), t**2*exp(-t)/2,         0,           0,         0,              0,             0],
[      0,   exp(-t),      t*exp(-t),         0,           0,         0,              0,             0],
[      0,         0,        exp(-t),         0,           0,         0,              0,             0],
[      0,         0,              0, exp(-2*t), t*exp(-2*t),         0,              0,             0],
[      0,         0,              0,         0,   exp(-2*t),         0,              0,             0],
[      0,         0,              0,         0,           0, exp(-3*t),              0,             0],
[      0,         0,              0,         0,           0,         0,  exp(t)*cos(t), exp(t)*sin(t)],
[      0,         0,              0,         0,           0,         0, -exp(t)*sin(t), exp(t)*cos(t)]])

In [44]:
expAt = P@expJt@Matrix(P).inv()
expAt

Matrix([
[               6*t**2*exp(-t)/5 - 42*t*exp(-t)/25 - 6*t*exp(-2*t)/5 + 78*exp(t)*sin(t)/2125 + 6*exp(t)*cos(t)/2125 + 597*exp(-t)/125 - 93*exp(-2*t)/25 - exp(-3*t)/17,             14*t**2*exp(-t)/5 - 158*t*exp(-t)/25 - 17*t*exp(-2*t)/5 + 302*exp(t)*sin(t)/2125 - 16*exp(t)*cos(t)/2125 + 1303*exp(-t)/125 - 256*exp(-2*t)/25 - 3*exp(-3*t)/17,            17*t**2*exp(-t)/10 - 279*t*exp(-t)/50 - 14*t*exp(-2*t)/5 + 871*exp(t)*sin(t)/4250 - 273*exp(t)*cos(t)/4250 + 4103*exp(-t)/500 - 399*exp(-2*t)/50 - 11*exp(-3*t)/68,        -t*exp(-t)/5 - 3*t*exp(-2*t)/10 + 52*exp(t)*sin(t)/425 - 111*exp(t)*cos(t)/850 + 37*exp(-t)/50 - 29*exp(-2*t)/50 - exp(-3*t)/34,                 7*t**2*exp(-t)/20 - 29*t*exp(-t)/100 - t*exp(-2*t)/5 + 14*exp(t)*sin(t)/2125 - 267*exp(t)*cos(t)/2125 + 853*exp(-t)/1000 - 18*exp(-2*t)/25 - exp(-3*t)/136,               3*t**2*exp(-t)/4 - 39*t*exp(-t)/20 - t*exp(-2*t) - 11*exp(t)*sin(t)/425 - 27*exp(t)*cos(t)/425 + 623*exp(-t)/200 - 3*exp(-2*t) - 7*exp(-3*t)/136,        

In [45]:
X = P@expJt
X

Matrix([
[-2*exp(-t), -2*t*exp(-t) - 3*exp(-t),  -t**2*exp(-t) - 3*t*exp(-t) - 3*exp(-t),    3*exp(-2*t),    3*t*exp(-2*t) + 10*exp(-2*t),       exp(-3*t),     -exp(t)*sin(t) + exp(t)*cos(t),      exp(t)*sin(t) + exp(t)*cos(t)],
[ 2*exp(-t),    2*t*exp(-t) + exp(-t),                 t**2*exp(-t) + t*exp(-t),   -6*exp(-2*t),   -6*t*exp(-2*t) - 17*exp(-2*t),    -3*exp(-3*t),                   -2*exp(t)*sin(t),                    2*exp(t)*cos(t)],
[-2*exp(-t),   -2*t*exp(-t) + exp(-t),      -t**2*exp(-t) + t*exp(-t) + exp(-t),   12*exp(-2*t),   12*t*exp(-2*t) + 28*exp(-2*t),     9*exp(-3*t), -2*exp(t)*sin(t) - 2*exp(t)*cos(t), -2*exp(t)*sin(t) + 2*exp(t)*cos(t)],
[ 2*exp(-t),  2*t*exp(-t) - 3*exp(-t),               t**2*exp(-t) - 3*t*exp(-t),  -24*exp(-2*t),  -24*t*exp(-2*t) - 44*exp(-2*t),   -27*exp(-3*t),                   -4*exp(t)*cos(t),                   -4*exp(t)*sin(t)],
[-2*exp(-t), -2*t*exp(-t) + 5*exp(-t),  -t**2*exp(-t) + 5*t*exp(-t) - 3*exp(-t),   48*exp(-2*t),   48*t*exp(-2*

In [46]:
diff(X,t) - A@X

Matrix([
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0]])

In [47]:
diff(expAt,t) - A@expAt

Matrix([
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0]])

## Technique used in an introductory differential equations course.

We typically give students the following "cookbook" approach to solving this problem.

### Starting with the differential equation
Differential equation
$$
    y^{(8)}+8y^{(7)}+22y^{(6)}+22y^{(5)}+7y^{(4)}+34y^{(3)}+90\ddot y+80\dot y+24 y = 0.
$$
form the **characteristic polynomial of the differential equation**
$$
    p(r) = r^{8} + 8 r^{7} + 22 r^{6} + 22 r^{5} + 7 r^{4} + 34 r^{3} + 90 r^{2} + 80 r + 24
$$
Notice that this is the same as the characteristic polynomial of the matrix $A$.

In [48]:
r = Symbol('r')
p = Matrix(A).charpoly(r).as_expr()
p

r**8 + 8*r**7 + 22*r**6 + 22*r**5 + 7*r**4 + 34*r**3 + 90*r**2 + 80*r + 24

In [49]:
p.factor()

(r + 1)**3*(r + 2)**2*(r + 3)*(r**2 - 2*r + 2)

In [50]:
y1,y2,y3 = exp(-t),t*exp(-t),t**2*exp(-t)
y4,y5 = exp(-2*t),t*exp(-2*t)
y6 = exp(-3*t)
y7,y8 = exp(t)*cos(t),exp(t)*sin(t)

In [51]:
row = [y1,y2,y3,y4,y5,y6,y7,y8]
rows = [row]
for k in range(1,8):
    row = [diff(yi,t) for yi in rows[-1]]
    rows.append(row)
X = Matrix(rows)
X

Matrix([
[ exp(-t),              t*exp(-t),                              t**2*exp(-t),      exp(-2*t),                      t*exp(-2*t),       exp(-3*t),                      exp(t)*cos(t),                      exp(t)*sin(t)],
[-exp(-t),   -t*exp(-t) + exp(-t),               -t**2*exp(-t) + 2*t*exp(-t),   -2*exp(-2*t),       -2*t*exp(-2*t) + exp(-2*t),    -3*exp(-3*t),     -exp(t)*sin(t) + exp(t)*cos(t),      exp(t)*sin(t) + exp(t)*cos(t)],
[ exp(-t),  t*exp(-t) - 2*exp(-t),    t**2*exp(-t) - 4*t*exp(-t) + 2*exp(-t),    4*exp(-2*t),      4*t*exp(-2*t) - 4*exp(-2*t),     9*exp(-3*t),                   -2*exp(t)*sin(t),                    2*exp(t)*cos(t)],
[-exp(-t), -t*exp(-t) + 3*exp(-t),   -t**2*exp(-t) + 6*t*exp(-t) - 6*exp(-t),   -8*exp(-2*t),    -8*t*exp(-2*t) + 12*exp(-2*t),   -27*exp(-3*t), -2*exp(t)*sin(t) - 2*exp(t)*cos(t), -2*exp(t)*sin(t) + 2*exp(t)*cos(t)],
[ exp(-t),  t*exp(-t) - 4*exp(-t),   t**2*exp(-t) - 8*t*exp(-t) + 12*exp(-t),   16*exp(-2*t),    16*t*exp(-2*t) - 32*ex

In [53]:
X.det().simplify()

-3400000*exp(-8*t)

In [54]:
diff(X,t)-A@X

Matrix([
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0]])

## Hartman-Grobman Theorem
$\newcommand{\xstar}{x^{\star}}$
$\newcommand{\R}{{\Bbb R}}$
https://en.wikipedia.org/wiki/Hartman–Grobman_theorem

### Hypotheses
1. Let $U$ be an **open neighborhood** of $x^{\star}$ in ${\Bbb R}^n$.  That is $U$ is open (all points of $U$ are interior points) and contains $x^{\star}$.

2. Let $f:U\to{\Bbb R}^n$ be $C^{1}$ on $U$ (continuous partial derivatives of the components w.r.t. the usual coordinates).

3. Let $J$ be the Jacobian matrix
$$
    J = [J_{ij}] = [\partial f_i/\partial x_j].
$$

4. Let $\phi(t,y_0)=\phi^t(y_0)=\phi_{y_0}(t)$ be the **flow** for 
\begin{equation}
    \dot y = f(y),\qquad y(0)=y_0. \tag{IVP}
\end{equation}
That is, for each initial condition $y_0\in U$, $\phi_{y_0}(t)$ satisfies (IVP) on some open interval about $t=0$. 

5. Suppose $x^{\star}$ is an **equilibrium point** (or **fixed point**) for $f$.  That is, $f(x^{\star})=0$ hence
$$
    \phi(t,x^{\star}) \equiv x^{\star}.
$$

6. Suppose $A=J(x^{\star})$ is **hyperbolic**.  That is, all eigenvalues of $A$ have nonzero real part.

### Conclusion
#### Then
1. there is a **neighborhood** $N$ of $x^{\star}$ (a set with $x^{\star}$ in its interior), 

2. a neighborhood $V$ of $0$ in ${\Bbb R}^n$, and

3. a **homeomorphism** $h:N\to V$, that is $h$ is continuous, invertible, and its inverse is continuous

#### such that
* under the change of coordinates $x=h(y)$ the flow $\phi$ is topologically conjugate to the flow for the linear system
$$
    \dot x = Ax\qquad x(t_0) = x_0
$$
which as we now know is $e^{At}x_0$.  That is, $h(\phi(t,y_0))=e^{At}x_0$ with $x_0=h(y_0)$.