## The exponential of a matrix
Let $A$ be an $n\times n$ matrix.  Then
$$
    e^{At} = I + At + {A^2t^2\over 2} + {A^3t^3\over 3!} +\ldots = \sum_{k=0}^{\infty} {A^kt^k\over k!}.
$$
is a fundamental matrix solution of
$$
    \boldsymbol y' = A\boldsymbol y
$$
with
$$
    e^{A0} = I\qquad\hbox{and}\qquad\left(e^{At}\right)^{-1} = e^{-At}.
$$

## Canonical Forms
Suppose $A$ is similar to $J$.  That is, there is an invertible matrix $P$ such that 
$$
    A = PJP^{-1}
$$
or
$$
    AP = PJ
$$

Then
$$
    e^{At} = I + At+ {A^2t^2\over 2} + {A^3t^3\over 3!} +\cdots
    =  PP^{-1}+ PJtP^{-1} + {PJ^2t^2P^{-1}\over 2} +\cdots = P e^Jt P^{-1} $$
    

## Complex Eigenvalues
Suppose
$$
    J = \begin{bmatrix} \alpha & \beta\cr -\beta & \alpha \cr\end{bmatrix}
    = \alpha \begin{bmatrix} 1 & 0 \\ 0 & 1\end{bmatrix} 
     + \beta \begin{bmatrix} 0 & 1\cr -1 & 0 \cr\end{bmatrix} = \alpha I + \beta B.
$$
Since the identity matrix commutes with any $2\times2$ matrix,
$$
    e^{Jt} = e^{\alpha I t} e^{B t}.
$$
Furthermore
$$
    e^{Jt} = e^{\alpha I t}e^{Bt} = e^{\alpha t}\begin{bmatrix}
    \cos \beta t & \sin\beta t\cr
    -\sin\beta t & \cos\beta t\cr
    \end{bmatrix}
$$

In [33]:
import numpy as np
import numpy.linalg as LA
from sympy import Symbol, Matrix, diag, diff, exp, cos, sin

## Example
Find a fundamental matrix solution for
$$
    y' = Ay
$$

In [2]:
A = np.array(
[[  3,  -8, -16,   1, -10],
 [ -2,  11,  16,   0,  14],
 [  0,   1,   0,   1,   3],
 [  0,  10,  10,   1,  15],
 [  2, -10, -14,  -1, -15]]
)
A

array([[  3,  -8, -16,   1, -10],
       [ -2,  11,  16,   0,  14],
       [  0,   1,   0,   1,   3],
       [  0,  10,  10,   1,  15],
       [  2, -10, -14,  -1, -15]])

In [3]:
λ,V = LA.eig(A)
λ

array([-1.+1.j, -1.-1.j, -1.+0.j,  1.+0.j,  2.+0.j])

In [4]:
Matrix(A).eigenvals()

{2: 1, 1: 1, -1: 1, -1 - I: 1, -1 + I: 1}

In [7]:
λ

array([-1.+1.j, -1.-1.j, -1.+0.j,  1.+0.j,  2.+0.j])

In [8]:
u1w1,_,v2,v3,v4 = V.T

In [9]:
u1w1

array([-3.16227766e-01+1.58113883e-01j,  7.18102499e-16+1.82772168e-15j,
       -3.16227766e-01+1.58113883e-01j, -7.90569415e-01+0.00000000e+00j,
        3.16227766e-01-1.58113883e-01j])

In [10]:
u1w1/u1w1[0].imag

array([-2.00000000e+00+1.00000000e+00j,  4.54167898e-15+1.15595269e-14j,
       -2.00000000e+00+1.00000000e+00j, -5.00000000e+00+0.00000000e+00j,
        2.00000000e+00-1.00000000e+00j])

In [20]:
u1 = np.array([-2,0,-2,-5,2])
w1 = np.array([1,0,1,0,-1])
u1,w1

(array([-2,  0, -2, -5,  2]), array([ 1,  0,  1,  0, -1]))

In [21]:
α,β = -1,1
u1w1 = Matrix(np.array([u1,w1]).T)
u1w1

Matrix([
[-2,  1],
[ 0,  0],
[-2,  1],
[-5,  0],
[ 2, -1]])

In [52]:
J1 = np.array([[α,β],[-β,α]])
A@u1w1 - u1w1@J1

Matrix([
[0, 0],
[0, 0],
[0, 0],
[0, 0],
[0, 0]])

In [23]:
v2

array([-8.16496581e-01+0.j,  4.08248290e-01+0.j, -4.08248290e-01+0.j,
        1.40178135e-14+0.j, -5.77232090e-15+0.j])

In [24]:
v2/v2[1]

array([-2.00000000e+00+0.j,  1.00000000e+00+0.j, -1.00000000e+00+0.j,
        3.43364903e-14+0.j, -1.41392408e-14+0.j])

In [25]:
w2 = np.array([-2,1,-1,0,0])
A@w2 + w2

array([0, 0, 0, 0, 0])

In [26]:
v3

array([ 7.74596669e-01+0.j, -2.58198890e-01+0.j,  2.58198890e-01+0.j,
        5.16397779e-01+0.j, -3.58953035e-16+0.j])

In [27]:
v3/v3[2]

array([ 3.00000000e+00+0.j, -1.00000000e+00+0.j,  1.00000000e+00+0.j,
        2.00000000e+00+0.j, -1.39021913e-15+0.j])

In [28]:
w3 = np.array([3,-1,1,2,0])
A@w3 - w3

array([0, 0, 0, 0, 0])

In [29]:
v4

array([-6.57595949e-01+0.j,  6.57595949e-01+0.j, -1.64398987e-01+0.j,
        1.23007162e-15+0.j, -3.28797975e-01+0.j])

In [30]:
v4/v4[2]

array([ 4.00000000e+00-0.j, -4.00000000e+00-0.j,  1.00000000e+00-0.j,
       -7.48223355e-15-0.j,  2.00000000e+00-0.j])

In [31]:
w4 = np.array([4,-4,1,0,2])
A@w4 - 2*w4

array([0, 0, 0, 0, 0])

In [35]:
t = Symbol('t')
expJ1t = exp(α*t)*Matrix([[cos(β*t),sin(β*t)],[-sin(β*t),cos(β*t)]])
expJ1t

Matrix([
[ exp(-t)*cos(t), exp(-t)*sin(t)],
[-exp(-t)*sin(t), exp(-t)*cos(t)]])

In [39]:
x = u1w1*expJ1t
diff(x,t) - A@x

Matrix([
[0, 0],
[0, 0],
[0, 0],
[0, 0],
[0, 0]])

In [40]:
x

Matrix([
[-exp(-t)*sin(t) - 2*exp(-t)*cos(t), -2*exp(-t)*sin(t) + exp(-t)*cos(t)],
[                                 0,                                  0],
[-exp(-t)*sin(t) - 2*exp(-t)*cos(t), -2*exp(-t)*sin(t) + exp(-t)*cos(t)],
[                 -5*exp(-t)*cos(t),                  -5*exp(-t)*sin(t)],
[ exp(-t)*sin(t) + 2*exp(-t)*cos(t),  2*exp(-t)*sin(t) - exp(-t)*cos(t)]])

In [42]:
x = Matrix(w2*exp(-t))
x

Matrix([
[-2*exp(-t)],
[   exp(-t)],
[  -exp(-t)],
[         0],
[         0]])

In [43]:
diff(x,t) - A*x

Matrix([
[0],
[0],
[0],
[0],
[0]])

In [51]:
expJt = diag(expJ1t,exp(-t),exp(t),exp(2*t))
expJt

Matrix([
[ exp(-t)*cos(t), exp(-t)*sin(t),       0,      0,        0],
[-exp(-t)*sin(t), exp(-t)*cos(t),       0,      0,        0],
[              0,              0, exp(-t),      0,        0],
[              0,              0,       0, exp(t),        0],
[              0,              0,       0,      0, exp(2*t)]])

In [55]:
P = Matrix(np.vstack([u1,w1,w2,w3,w4]).T)
P

Matrix([
[-2,  1, -2,  3,  4],
[ 0,  0,  1, -1, -4],
[-2,  1, -1,  1,  1],
[-5,  0,  0,  2,  0],
[ 2, -1,  0,  0,  2]])

In [56]:
expAt = P@expJt@P.inv()
expAt

Matrix([
[       3*exp(t) - 2*exp(-t)*sin(t) - 2*exp(-t), -4*exp(2*t) + 4*exp(-t)*sin(t) - 2*exp(-t)*cos(t) + 6*exp(-t), -4*exp(2*t) - 6*exp(t) + 8*exp(-t)*sin(t) - 2*exp(-t)*cos(t) + 12*exp(-t),                    exp(-t)*sin(t), -4*exp(2*t) - 3*exp(t) + 8*exp(-t)*sin(t) - 3*exp(-t)*cos(t) + 10*exp(-t)],
[                             -exp(t) + exp(-t),                                        4*exp(2*t) - 3*exp(-t),                                         4*exp(2*t) + 2*exp(t) - 6*exp(-t),                                 0,                                           4*exp(2*t) + exp(t) - 5*exp(-t)],
[           exp(t) - 2*exp(-t)*sin(t) - exp(-t),   -exp(2*t) + 4*exp(-t)*sin(t) - 2*exp(-t)*cos(t) + 3*exp(-t),    -exp(2*t) - 2*exp(t) + 8*exp(-t)*sin(t) - 2*exp(-t)*cos(t) + 6*exp(-t),                    exp(-t)*sin(t),      -exp(2*t) - exp(t) + 8*exp(-t)*sin(t) - 3*exp(-t)*cos(t) + 5*exp(-t)],
[2*exp(t) - 4*exp(-t)*sin(t) - 2*exp(-t)*cos(t),                                             10*e

In [57]:
diff(expAt,t) - A@expAt

Matrix([
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0]])

In [58]:
expAt.subs(t,0)

Matrix([
[1, 0, 0, 0, 0],
[0, 1, 0, 0, 0],
[0, 0, 1, 0, 0],
[0, 0, 0, 1, 0],
[0, 0, 0, 0, 1]])

In [60]:
X = P@expJt
X

Matrix([
[-exp(-t)*sin(t) - 2*exp(-t)*cos(t), -2*exp(-t)*sin(t) + exp(-t)*cos(t), -2*exp(-t), 3*exp(t),  4*exp(2*t)],
[                                 0,                                  0,    exp(-t),  -exp(t), -4*exp(2*t)],
[-exp(-t)*sin(t) - 2*exp(-t)*cos(t), -2*exp(-t)*sin(t) + exp(-t)*cos(t),   -exp(-t),   exp(t),    exp(2*t)],
[                 -5*exp(-t)*cos(t),                  -5*exp(-t)*sin(t),          0, 2*exp(t),           0],
[ exp(-t)*sin(t) + 2*exp(-t)*cos(t),  2*exp(-t)*sin(t) - exp(-t)*cos(t),          0,        0,  2*exp(2*t)]])

## Simpler fundamental matrix.
If $Q$ is an invertible matrix, then the columns of
$$
    X(t) = e^{At} Q
$$
are
1. linearly independent for all $t$, and
2. are all linear combinations of the columns of $e^{At}$.
It follows that $X(t)$ is a fundamental matrix solution of 
$$
    y' = Ay
$$

In particular,
$$
    X(t) = e^{At}P = Pe^{Jt}
$$
is also a fundamental matrix solution.

## Example
No basis of eigenvectors

In [62]:
A = np.array([[1,1],[0,1]])
A

array([[1, 1],
       [0, 1]])

Notice that one is the only eigenvalue and
$$
A  - I = \begin{bmatrix} 0 & 1\cr 0 & 0 \end{bmatrix}
$$
has a one dimensional null space spanned by
$$
    \begin{bmatrix} 1 \\ 0 \end{bmatrix}.
$$

This is a standard example of a matrix without a basis of eigenvectors.

Notice
$$
    A = I + \begin{bmatrix} 0 & 1\cr 0 & 0 \end{bmatrix} = I + N
$$
with
$$
    N^2 = 0.
$$

It follows that
$$
    e^{Nt} = I + Nt + 0
$$
and 
$$
    e^{At} = e^{t}e^{Nt}.
$$

In [63]:
A = Matrix([[1,1],[0,1]])
expAt = exp(t)*Matrix([[1,t],[0,1]])
expAt

Matrix([
[exp(t), t*exp(t)],
[     0,   exp(t)]])

In [65]:
diff(expAt,t)-A*expAt

Matrix([
[0, 0],
[0, 0]])

## Differential Equation:
$$
    y^{(8)}+8y^{(7)}+22y^{(6)}+22y^{(5)}+7y^{(4)}+34y^{(3)}+90 y^{(2)}+80 y'+24 y= 0
$$