## The exponential of a matrix
Let $A$ be an $n\times n$ matrix.  Recall that
$$
    X(t) = e^{At} = I + At + {A^2t^2\over 2} + {A^3t^3\over 3!} +\ldots = \sum_{k=0}^{\infty} {A^kt^k\over k!}
$$
is a fundamental matrix solution of
$$
    \boldsymbol y' = A\boldsymbol y
$$
and
$$
    \left(X(t)\right)^{-1} = X(-t) = e^{-At}.
$$

## Canonical Forms
Suppose $A$ is similar to $J$.  That is, suppose there is an invertible matrix $P$ such that 
$$
    AP = PJ\qquad\hbox{or}\qquad A = PJP^{-1}
$$
then
$$
    e^{At} = P e^{Jt} P^{-1}.
$$

## Complex Eigenvalues
Suppose
$$
    J = \begin{bmatrix} \alpha & \beta\cr -\beta & \alpha \cr\end{bmatrix}
    = \alpha \begin{bmatrix} 1 & 0 \\ 0 & 1\end{bmatrix} 
     + \beta \begin{bmatrix} 0 & 1\cr -1 & 0 \cr\end{bmatrix} = \alpha I + \beta B.
$$
Since the identity matrix commutes with any $2\times2$ matrix,
$$
    e^{Jt} = e^{\alpha I t} e^{B t}.
$$
Furthermore
$$
    e^{Jt} = e^{\alpha I t}e^{Bt} = e^{\alpha t}\begin{bmatrix}
    \cos \beta t & \sin\beta t\cr
    -\sin\beta t & \cos\beta t\cr
    \end{bmatrix}
$$

## Block Diagonal Matrices

If $J$ is a block diagonal matrix, say
$$
    J = \begin{bmatrix}
        J_1 & 0 & 0 & \cdots & 0 \\
        0 & J_2 & 0 & \cdots & 0 \\
        0 & 0 & J_3 & \cdots & 0 \\
        \vdots & \vdots & \vdots & \ddots & \vdots \\
        0 & 0 & 0 &\cdots &J_m\\
    \end{bmatrix}
$$
where each $J_i$ is a square matrix, then

$$
    J^kt^k = \begin{bmatrix}
        J_1^k t^k & 0 & 0 & \cdots & 0 \\
        0 & J_2^k t^k & 0 & \cdots & 0 \\
        0 & 0 & J_3^k t^k & \cdots & 0 \\
        \vdots & \vdots & \vdots & \ddots & \vdots \\
        0 & 0 & 0 &\cdots &J_m^k t^k\\
    \end{bmatrix}
$$

and
$$
    e^{Jt} = \sum_{k=0}^{\infty} {J^k t^k\over k!}
    =\begin{bmatrix} 
        e^{J_1 t} & 0 & 0 & \cdots & 0 \\
        0 & e^{J_2 t} & 0 & \cdots & 0 \\
        0 & 0 & e^{J_3 t} & \cdots & 0 \\
        \vdots & \vdots & \vdots & \ddots & \vdots \\
        0 & 0 & 0 &\cdots &e^{J_m t}\\
    \end{bmatrix}
$$

In [25]:
import numpy as np, math
import numpy.linalg as LA
from math import pi as π
from sympy import Symbol, Matrix, diag, diff, exp, cos, sin, factor

## Differential Equation:
$$
    y^{(8)}+8y^{(7)}+22y^{(6)}+22y^{(5)}+7y^{(4)}+34y^{(3)}+90 y^{(2)}+80 y'+24 y= 0
$$
Equivalent first order system
\begin{align*}
\dot y = \dot y_1 &= y_2\cr
\dot y_2 &= y_3\cr
&\vdots\cr
\dot y_7 &=y_8\cr
\dot y_8 &= - 8y_8-22y_7-22y_6-7y_5-34y_4-90y_3-80y_2-24y_1\cr
\end{align*}

In [24]:
A = np.eye(8,8,1,dtype=int)
A[-1] = [-24,-80,-90,-34,-7,-22,-22,-8]
A

array([[  0,   1,   0,   0,   0,   0,   0,   0],
       [  0,   0,   1,   0,   0,   0,   0,   0],
       [  0,   0,   0,   1,   0,   0,   0,   0],
       [  0,   0,   0,   0,   1,   0,   0,   0],
       [  0,   0,   0,   0,   0,   1,   0,   0],
       [  0,   0,   0,   0,   0,   0,   1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   1],
       [-24, -80, -90, -34,  -7, -22, -22,  -8]])

In [26]:
λ,V = LA.eig(A)
λ

array([-3.        +0.00000000e+00j,  1.        +1.00000000e+00j,
        1.        -1.00000000e+00j, -2.00000007+0.00000000e+00j,
       -1.99999993+0.00000000e+00j, -1.00001484+0.00000000e+00j,
       -0.99999258+1.28500039e-05j, -0.99999258-1.28500039e-05j])

In [27]:
LA.norm(LA.inv(V)@V-np.eye(8),1)

np.float64(110.00051133658953)

In [28]:
f'{LA.cond(V):.3e}'

'1.213e+11'

In [29]:
LA.norm(A@V - V@np.diag(λ),2) 

np.float64(1.5359097157862368e-13)

In [32]:
factor(Matrix(A).charpoly().as_poly())

Poly(lambda**8 + 8*lambda**7 + 22*lambda**6 + 22*lambda**5 + 7*lambda**4 + 34*lambda**3 + 90*lambda**2 + 80*lambda + 24, lambda, domain='ZZ')

In [33]:
Matrix(A).eigenvals()

{-3: 1, -2: 2, -1: 3, 1 - I: 1, 1 + I: 1}

### Eigenvalue -1
This eigenvalue has algebraic multiplicity 3, but what is the geometric multiplicity?  This must be the dimension of the nullspace of 
$A+I.$

In [37]:
v1 = V.T[5]
v1/v1[-1]

array([-0.99989614+0.j,  0.99991097+0.j, -0.99992581+0.j,  0.99994065+0.j,
       -0.99995549+0.j,  0.99997032+0.j, -0.99998516+0.j,  1.        +0.j])

In [43]:
w1 = 2*np.array([-1,1,-1,1,-1,1,-1,1])
A@w1 + w1

array([0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
I8 = np.eye(8,dtype=int)
LA.matrix_rank(A+I8)

np.int64(7)

In [45]:
LA.matrix_rank(LA.matrix_power(A+I8,2))

np.int64(6)

In [46]:
v2 = LA.solve((A+I8),w1)
v2

array([ -3.,   1.,   1.,  -3.,   5.,  -7.,   9., -11.])

In [47]:
w2 = np.array([-3,1,1,-3,5,-7,9,-11])
(A+I8)@w2 - w1

array([0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
LA.matrix_rank(LA.matrix_power(A+I8,3))

np.int64(5)

In [49]:
v3 = LA.solve(A+I8,w2)
v3

array([-3.00000000e+00,  3.80647894e-16,  1.00000000e+00,  0.00000000e+00,
       -3.00000000e+00,  8.00000000e+00, -1.50000000e+01,  2.40000000e+01])

In [50]:
w3 = np.array([-3,0,1,0,-3,8,-15,24])
(A+I8)@w3 - w2

array([0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
J1 = np.array([[-1,1,0],[0,-1,1],[0,0,-1]])
J1

array([[-1,  1,  0],
       [ 0, -1,  1],
       [ 0,  0, -1]])

In [55]:
w1w2w3 = np.vstack((w1,w2,w3)).T
w1w2w3

array([[ -2,  -3,  -3],
       [  2,   1,   0],
       [ -2,   1,   1],
       [  2,  -3,   0],
       [ -2,   5,  -3],
       [  2,  -7,   8],
       [ -2,   9, -15],
       [  2, -11,  24]])

In [56]:
A@w1w2w3 - w1w2w3@J1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Eigenvalue -2

In [58]:
v4 = V.T[3]
v4/v4[0]

array([   1.        +0.j,   -2.00000007+0.j,    4.00000028+0.j,
         -8.00000083+0.j,   16.00000221+0.j,  -32.00000553+0.j,
         64.00001328+0.j, -128.00003098+0.j])

In [59]:
λ2 = -2
w4 = 3*np.array([1,-2,4,-8,16,-32,64,-128])
A@w4 + 2*w4

array([0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
v5 = LA.solve(A+2*I8,w4)
v5

LinAlgError: Singular matrix

In [61]:
res = LA.lstsq(A+2*I8,w4)
res

(array([ 10.00018311, -17.00036622,  28.00073243, -44.00146487,
         64.00292973, -80.00585946,  64.01171893,  63.97656214]),
 array([], dtype=float64),
 np.int32(7),
 array([1.31502891e+02, 2.84573100e+00, 2.59574906e+00, 2.25675302e+00,
        1.89321276e+00, 1.47373187e+00, 1.14215180e+00, 3.31175540e-18]))

In [62]:
w5 = np.array([10,-17,28,-44,64,-80,64,64])
(A+2*I8)@w5 - w4

array([0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
w4w5 = np.vstack((w4,w5)).T
J2 = np.array([[-2,1],[0,-2]])
A@w4w5 - w4w5@J2

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

## Eigenvector -3

In [65]:
v6 = V.T[0]
v6/v6[0]

array([ 1.000e+00+0.j, -3.000e+00+0.j,  9.000e+00+0.j, -2.700e+01+0.j,
        8.100e+01+0.j, -2.430e+02+0.j,  7.290e+02+0.j, -2.187e+03+0.j])

In [66]:
w6 = np.array([1,-3,9,-27,81,-243,729,-2187])
A@w6 + 3*w6

array([0, 0, 0, 0, 0, 0, 0, 0])

In [67]:
J3 = np.array([[-3]])
J3

array([[-3]])

### Eigenvalue $\lambda = 1+i$ of multiplicity $1$

In [ ]:
α,β = 1,1
